export const locationData = [
  "Australia",
  "Bangladesh",
  "Bhutan",
  "Brazil",
  "Brunei",
  "Cambodia",
  "Canada",
  "China",
  "Fiji",
  "France",
  "Germany",
  "Hong Kong",
  "India",
  "Indonesia",
  "Iran",
  "Israel",
  "Japan",
  "Jordan",
  "Kenya",
  "Laos",
  "Macau",
  "Malaysia",
  "Maldives",
  "Mexico",
  "Myanmar",
  "Nepal",
  "New Zealand",
  "Nigeria",
  "Papua New Guinea",
  "Pakistan",
  "Philippines",
  "Qatar",
  "Saudi Arabia",
  "Singapore",
  "South Africa",
  "South Korea",
  "Sri Lanka",
  "Taiwan",
  "Thailand",
  "Turkey",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "Vietnam"
];


export const educationLevels = [
  "High School",
  "Certificate",
  "Diploma",
  "Associate Degree",
  "Bachelor's Degree",
  "Master's Degree",
  "Doctorate (PhD)",
  "Professional Certification"
];

export const languages = [
  "Arabic",
  "Bengali",
  "Burmese",
  "Dutch",
  "English",
  "French",
  "German",
  "Gujarati",
  "Hebrew",
  "Hindi",
  "Indonesian",
  "Italian",
  "Japanese",
  "Khmer",
  "Korean",
  "Lao",
  "Malay",
  "Mandarin",
  "Marathi",
  "Persian",
  "Polish",
  "Portuguese",
  "Punjabi",
  "Russian",
  "Spanish",
  "Swahili",
  "Tagalog",
  "Tamil",
  "Telugu",
  "Thai",
  "Turkish",
  "Urdu",
  "Vietnamese"
];


export const proficiencyLevels = ["Beginner", "Intermediate", "Expert", "Native"]
