export const locationData = [
  "Australia",
  "Bangladesh",
  "Bhutan",
  "Brazil",
  "Brunei",
  "Cambodia",
  "Canada",
  "China",
  "Fiji",
  "France",
  "Germany",
  "Hong Kong",
  "India",
  "Indonesia",
  "Iran",
  "Israel",
  "Japan",
  "Jordan",
  "Kenya",
  "Laos",
  "Macau",
  "Malaysia",
  "Maldives",
  "Mexico",
  "Myanmar",
  "Nepal",
  "New Zealand",
  "Nigeria",
  "Papua New Guinea",
  "Pakistan",
  "Philippines",
  "Qatar",
  "Saudi Arabia",
  "Singapore",
  "South Africa",
  "South Korea",
  "Sri Lanka",
  "Taiwan",
  "Thailand",
  "Turkey",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "Vietnam"
];


export const educationLevels = [
  "High School",
  "Certificate",
  "Diploma",
  "Associate Degree",
  "Bachelor's Degree",
  "Master's Degree",
  "Doctorate (PhD)",
  "Professional Certification"
];


export const jobCategories = [
  "Freelance",
  "Part Time",
  "Gig Internship"
]

export const jobTitles = [
  "Accountant",
  "AI/ML Engineer",
  "App Tester",
  "Backend Developer",
  "Business Analyst",
  "Community Builder",
  "Content Writer",
  "Copywriter",
  "Customer Support",
  "Data Analyst",
  "Data Entry Clerk",
  "Digital Marketing Specialist",
  "Frontend Developer",
  "Full Stack Developer",
  "Game Developer",
  "Graphic Designer",
  "HR Assistant",
  "Mobile App Developer",
  "Product Manager",
  "Project Manager",
  "QA Tester",
  "Sales Representative",
  "SEO Specialist",
  "Social Media Manager",
  "Software Engineer Intern",
  "Technical Support Specialist",
  "Translator",
  "UI/UX Designer",
  "Virtual Assistant",
  "Video Editor",
  "Web Designer",
  "Web Developer"
];


export const skillTags = [
  "Adobe Illustrator",
  "Adobe Photoshop",
  "Agile/Scrum",
  "Android Development",
  "C++",
  "Canva",
  "Content Writing",
  "Copywriting",
  "Customer Service",
  "Data Analysis",
  "Data Entry",
  "Email Marketing",
  "Excel",
  "Facebook Ads",
  "Figma",
  "Flutter",
  "Git/GitHub",
  "Google Ads",
  "Google Analytics",
  "HTML/CSS",
  "Java",
  "JavaScript",
  "Kotlin",
  "Marketing Strategy",
  "MongoDB",
  "MySQL",
  "Node.js",
  "PHP",
  "PowerBI",
  "Project Management",
  "Python",
  "React",
  "React Native",
  "SEO",
  "Shopify",
  "Social Media Marketing",
  "SQL",
  "Tableau",
  "Technical Writing",
  "Time Management",
  "TypeScript",
  "Video Editing",
  "Vue.js",
  "Web Design",
  "WordPress"
];

export const languages = [
  "Arabic",
  "Bengali",
  "Burmese",
  "Dutch",
  "English",
  "French",
  "German",
  "Gujarati",
  "Hebrew",
  "Hindi",
  "Indonesian",
  "Italian",
  "Japanese",
  "Khmer",
  "Korean",
  "Lao",
  "Malay",
  "Mandarin",
  "Marathi",
  "Persian",
  "Polish",
  "Portuguese",
  "Punjabi",
  "Russian",
  "Spanish",
  "Swahili",
  "Tagalog",
  "Tamil",
  "Telugu",
  "Thai",
  "Turkish",
  "Urdu",
  "Vietnamese"
];


export const proficiencyLevels = ["Beginner", "Intermediate", "Expert", "Native"]
